name: Tests with chromium
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_environment:
        description: Environment to test
        required: true
        type: choice
        default: STAGE
        options:
          - DEV
          - STAGE
          - QA
jobs:
  test:
    env:
      TEST_ENV: ${{ inputs.test_environment || 'STAGE' }}
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Chromium
      run: npx playwright install chromium
    - name: Run Playwright tests
      run: npx playwright test --reporter=list,html
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-results
        path: playwright-report/
        retention-days: 30
